### PR TITLE
Added parameter to control what is backed up (i.e. not do a full backup)

### PR DESCRIPTION
**Pull request by RaggedStaff**
Hi,

I've just enhanced the script slightly to allow a parameterised backup to be run (my full backup runs to about 40GB & the big stuff is all "safely" in containers). 

I also like to run backups of more critical apps daily vs a more comprehensive weekly backup.

Hope that all makes sense, ping me if you have any questions.

### CODE REVIEW

**Review by Nidal-Tech — APPROVED** [review]
Changes approved

**Comment by Nidal-Tech** [comment]
Changes approved. Many thanks @RaggedStaff

**Comment by RaggedStaff** [comment]
Hi @Nidal-Tech !

I think you [`Closed` the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request), rather than [`Merging` it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request).

I don't see the new parameter in your [`main` branch.](https://github.com/Nidal-Tech/backupynh/blob/main/backupynh.sh) :confused: 

Let me know if you'd like me to resubmit my PR (I can't reopen this one, but you may be able to as it's your repo) ?

**Comment by Nidal-Tech** [comment]
This wasn't my intention. I will check it tomorrow and let you know.

**Comment by Nidal-Tech** [comment]
Merged :-)

**Pull request merged**
